# Generated by Django 4.0.1 on 2022-02-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
